config = "config.toml"
datadir = "D:\\ws\\git\\OG\\build\\private\\node_1"
genkey = false
log_line_number = false
max_mined_hash = "0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
max_tx_hash = "0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
multifile_by_level = false
multifile_by_module = false
title = "OG configuration"

[annsensus]
  campaign = false
  campain = false
  consensus_path = "consensus1.json"
  disable = false
  disable_term_change = true
  genesis_pk = "0x01043cef2edf0803c8d8fb0abfa17b2bda8043e39d4c1b908e88c79cbba3a97f63c8dfcc4891747c2ff0e46324814dffe8be9e839257039ec0afc1bf03537570d62b;0x01048788655ee0f41a9eb62a16d1db29c91d45382ad55134232b3a1f6385909ae57e22daec27082fe6f13a723301c6517548e62f8f9cee06a5a603365db7c8f97396;0x0104629e855c11dfdd7d856140565c4cb23995953bb03669ed33bf21e4c3c36a4f82ce6642d34dc6cf2baa6480f76e31d274e74de6159b5499ae390adf158aa33be3;0x01042d8c926ae03995eb464d82e9d939cb4abe32a4db531ce1c9105e7980b7e3cf5459f3332ae172d32ad13074be21bc49febb3b0e9382a676653b025f00aee45c00"
  mode = "archive"
  partner_number = 4
  term_change_interval = 10
  threshold = 4

[auto_client]
  nonce_self_discipline = false

  [auto_client.archive]
    enabled = false
    interval_us = 500000

  [auto_client.sequencer]
    enabled = false
    interval_us = 5000000

  [auto_client.tx]
    account_ids = [0,1]
    enabled = false
    interval_mode = "random"
    interval_us = 500000

[crypto]
  algorithm = "secp256k1"

[dag]
  genesis_path = "genesis.json"

[db]
  name = "leveldb"

[debug]
  node_id = 1

[hub]
  disable_encrypt_gossip = false
  incoming_buffer_size = 100
  message_cache_expiration_seconds = 60
  message_cache_max_size = 30000
  outgoing_buffer_size = 100
  sync_cycle_ms = 10000

[leveldb]
  cache = 16
  handles = 16
  path = "rw/datadir_1"

[log]
  level = "debug"
  log_dir = ""

[p2p]
  bootstrap_node = false
  bootstrap_nodes = "onode://e27504dd0e54fa6b981be9fce34f1ada908add2618fba829070bf4b5063f7667573dd31004ae9902f8832a0f7a36de7922926dbd7ced337a0a9b98f0de5d2abf@127.0.0.1:8001"
  enable_sync = true
  enabled = true
  max_peers = 50
  network_id = 1
  no_encryption = false
  node_key = "eb648bcfd5345068054c420fba19cfc8fdcb4709ca6b79e704d08e343c7fed89"
  port = 8011

[profiling]
  port = 8013

[rpc]
  enabled = true
  port = 8010

[statedb]
  beat_expire_time_s = 300
  flush_timer_s = 5
  purge_timer_s = 10

[txpool]
  queue_size = 100
  reset_duration = 10
  timeout_confirmation_ms = 10000
  timeout_latest_seq_ms = 10000
  timeout_pool_queue_ms = 10000
  timeout_subscriber_ms = 10000
  tips_size = 1000
  tx_valid_time = 100
  tx_verify_time = 2

[websocket]
  enabled = true
  port = 8012
