config = "config.toml"
datadir = "build/"
genkey = true
log_line_number = true
max_mined_hash = "0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
max_tx_hash = "0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
multifile_by_level = true
multifile_by_module = false
title = "TOML Example"

[annsensus]
  campaign = false
  consensus_path = "consensus.json"
  disable = true
  disable_term_change = true
  genesis_pk = "0x0104994735dfcf60eb43bb5286334a7a83b622685fc3feb92247c65cc4b4cd55497fbc767f2e59a222abb650e5f411d9f7b6266b49439cdb348d859e33e89846bcaf;0x01046ce80b57488632dd7fc1488f5c2ed4746b16e2656b9ec7793f6f7d23663a5bd68ba37a00313d55042480c23b98b2cbee334eda939eab12a737f4a5d3e646da93;0x0104329ad4860f4835427efe677cecfda463e9fa0be722b41d64109197499b2804fbe9fa41416191c81fc9f819f83fad0a891a4eb3c5ee7d7122c8a6c948f71c8028;0x0104f25bceb564a148de47ba2725eaa4f88898d54dee044d8bbf75b4f209edd67a0e21ab145e249a5dd236a7bd9d7bb42ef24c30fb9da94d8001faac29588c61c45b"
  mode = "archive"
  partner_number = 4
  term_change_interval = 10
  threshold = 4

[crypto]
  algorithm = "secp256k1"

[dag]
  genesis_path = "genesis.json"

[db]
  name = "leveldb"

[debug]
  node_id = 1

[hub]
  disable_encrypt_gossip = false
  incoming_buffer_size = 100
  message_cache_expiration_seconds = 60
  message_cache_max_size = 30000
  outgoing_buffer_size = 100
  sync_cycle_ms = 10000

[leveldb]
  cache = 16
  handles = 16
  path = "rw/datadir_1"

[log]
  level = "trace"
  log_dir = "build/log/"

[p2p]
  bootstrap_node = false
  bootstrap_nodes = "onode://8f8e947f52fc5beac771bad7b997f47521c44a16719a585ccd1e8a0557f8c54d993225a6adfb9bb6a40232f0227cf88ab542ea4b1b4fd04116ee5119a552382b@47.100.222.11:30006"
  enable_sync = true
  enabled = true
  max_peers = 50
  network_id = 1
  no_encryption = false
  node_key = "6d4ce0f90b69ff9482fee9abe877c7797ab81618a74e97074190c13aa596aa79"
  port = 8001

[profiling]
  port = 8003

[rpc]
  enabled = true
  port = 8000

[statedb]
  beat_expire_time_s = 300
  flush_timer_s = 5
  purge_timer_s = 10

[tx_buffer]
  new_tx_queue_size = 1

[txpool]
  queue_size = 100
  reset_duration = 10
  timeout_confirmation_ms = 10000
  timeout_latest_seq_ms = 10000
  timeout_pool_queue_ms = 10000
  timeout_subscriber_ms = 10000
  tips_size = 1000
  tx_valid_time = 100
  tx_verify_time = 2

[websocket]
  enabled = true
  port = 8002
