# This is a TOML document.

title = "TOML Example"

[log]
level = "info"

[rpc]
enabled = true
port = 30000

[p2p]
enabled = true
bootstrap_node = true
port = 30001
max_peers = 3
network_id = 1
enable_sync = true
bootstrap_nodes = "enode://6caae3f8faba3a135e2bd21d48a3be09c45653c4484fe396ac28c838ffc6b6d203295a7f963162687ec7d402157bbfaf8b602017a26945b13a98dc5a7eb43b5c@192.168.45.163:30001"
#node_key = "3fa29b2f6b83e037e2573545a6d9c06c0809aeb929cc8c14f992546ae5530b7d"

[websocket]
enabled = true
port = 30002

[profiling]
port = 30003

[db]
name = "leveldb"

[leveldb]
path = "data/datadir"
cache = 16
handles = 16

[txpool]
queue_size = 100
tips_size = 1000
reset_duration = 10
tx_verify_time = 2
tx_valid_time = 100

[auto_client]
# whether auto_tx will maintain its own nonce records.
# false to query latest nonce every time.
nonce_self_discipline = true

[auto_client.sequencer]
enabled = true
interval_ms = 5000

[auto_client.tx]
enabled = true
interval_ms = 5000
account_ids = [0,1,3]
interval_mode = "random"

[debug]
node_id = 1

[hub]
sync_cycle_ms = 10000

[crypto]
algorithm = "secp256k1"

consensus = "dpos"

[dag]

