# This is a TOML document.

title = "TOML Example"

[log]
level = "warn"

[rpc]
enabled = true
port = 8000

[p2p]
enabled = true
port = 8001
max_peers = 50
static_nodes = "enode://6caae3f8faba3a135e2bd21d48a3be09c45653c4484fe396ac28c838ffc6b6d203295a7f963162687ec7d402157bbfaf8b602017a26945b13a98dc5a7eb43b5c@192.168.45.163:8001"

[websocket]
enabled = true
port = 8002

[profiling]
port = 8003

[db]
name = "leveldb"

[leveldb]
path = "datadir1"
cache = 16
handles = 16

[txpool]
queue_size = 100
tips_size = 1000
reset_duration = 10
tx_verify_time = 2
tx_valid_time = 100

[auto_sequencer]
enabled = true
interval_ms = 15000

[auto_tx]
enabled = true
count = 5
interval_ms = 1000

[debug]
node_id = 1


[dag]

# samples below

#[owner]
#name = "Tom Preston-Werner"
#dob = 1979-05-27T07:32:00-08:00 # First class dates
#
#[database]
#server = "192.168.1.1"
#ports = [ 8001, 8001, 8002 ]
#connection_max = 5000
#enabled = true
#
#[servers]
#
#  # Indentation (tabs and/or spaces) is allowed but not required
#  [servers.alpha]
#  ip = "10.0.0.1"
#  dc = "eqdc10"
#
#  [servers.beta]
#  ip = "10.0.0.2"
#  dc = "eqdc10"
#
#[clients]
#data = [ ["gamma", "delta"], [1, 2] ]
#
## Line breaks are OK when inside arrays
#hosts = [
#  "alpha",
#  "omega"
#]
